---
- name: Install neccessory package
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2

- name: Add repo for docker
#  yum_repository:
#    name: docker-ce
#    description: docker-ce repo add
#    baseurl: https://download.docker.com/linux/centos/docker-ce.repo
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: Install docker and its dependencies
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  notify:
    - docker status

- name: Start docker
  service:
    name: docker
    state: started
    enabled: yes
  become: true